name 'sre_challenge'
maintainer 'The Authors'
maintainer_email 'leeson9394@gmail.com'
license 'all_rights'
description 'Installs/Configures sre_challenge'
long_description 'Installs/Configures sre_challenge'
version '0.1.0'

depends 'selinux', '~> 0.9'
depends 'firewall', '~> 2.5'
